### ISSUE TITLE
sims packages doc links

### ISSUE THREAD

**Issue by rhiannonlynne** [lsst-sqre/www_lsst_io#210]
Wow, so I just found the super nice browsing aspect of lsst.io (again). 
I appreciate that sims packages are included in this page: https://www.lsst.io/simulations-guides/ 
but the simulations guides that are linked are obsolete (at least the packages are). 
Could you just link to the rubin-sim.lsst.io pages instead? Is there anything we'd need to update/do on our end?

**Comment by jonathansick** [comment]
Thanks for letting me know @rhiannonlynne. I'll update the site right now.
